package generatedbyassl.as.autonomicnetwork.asself_management.self_configuring;

import java.io.Serializable;
import generatedbyassl.as.*;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'inAutonomicNetworkConfiguration' (specified as FLUENT ASSL tier).
 */
public class INAUTONOMICNETWORKCONFIGURATION
	extends ASSLFLUENT
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'INAUTONOMICNETWORKCONFIGURATION' class.
	 */
	static private INAUTONOMICNETWORKCONFIGURATION oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  INAUTONOMICNETWORKCONFIGURATION (  )
	{
		vInitiatedByEvents.add( generatedbyassl.as.autonomicnetwork.events.TIMETOCONFIGURATION.getInstance() );
		generatedbyassl.as.autonomicnetwork.events.TIMETOCONFIGURATION.getInstance().addEventCatcher(this); //**** fluent registers for that event
		vTerminatedByEvents.add( generatedbyassl.as.autonomicnetwork.events.CONFIGURATIONDONE.getInstance() );
		generatedbyassl.as.autonomicnetwork.events.CONFIGURATIONDONE.getInstance().addEventCatcher(this); //**** fluent registers for that event
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'INAUTONOMICNETWORKCONFIGURATION' class.
	 */
	static public INAUTONOMICNETWORKCONFIGURATION getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new INAUTONOMICNETWORKCONFIGURATION();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method calls all the fluent-mapped actions in sequence.
	 */
	protected synchronized void callFluentActions (  )
	{
	}

}