package generatedbyassl.as.autonomicnetwork.actions;

import java.io.Serializable;
import generatedbyassl.as.ASSLACTION;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'Configuration' (specified as ACTION ASSL tier).
 */
public class CONFIGURATION
	extends ASSLACTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'CONFIGURATION' class.
	 */
	static private CONFIGURATION oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  CONFIGURATION (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'CONFIGURATION' class.
	 */
	static public CONFIGURATION getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new CONFIGURATION();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Triggers events in case the action is successfully performed.
	 */
	public void TRIGGERS (  )
	{
		generatedbyassl.as.autonomicnetwork.events.CONFIGURATIONDONE.getInstance().triggerEvent();
	}

}