package generatedbyassl.as.autonomicnetwork.actions;

import java.io.Serializable;
import generatedbyassl.as.ASSLACTION;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'ConfigureAutonomicNetwork' (specified as ACTION ASSL tier).
 */
public class CONFIGUREAUTONOMICNETWORK
	extends ASSLACTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'CONFIGUREAUTONOMICNETWORK' class.
	 */
	static private CONFIGUREAUTONOMICNETWORK oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  CONFIGUREAUTONOMICNETWORK (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'CONFIGUREAUTONOMICNETWORK' class.
	 */
	static public CONFIGUREAUTONOMICNETWORK getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new CONFIGUREAUTONOMICNETWORK();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Provides conditions to be fulfilled before processing the action.
	 */
	public boolean GUARDS (  )
	{
		boolean bResult = true;
		bResult =  generatedbyassl.as.autonomicnetwork.asself_management.self_configuring.INAUTONOMICNETWORKCONFIGURATION.getInstance().isFluentInitiated()  ;
		return bResult;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Embeds statements to be performed by the action if the GURADS conditions are fulfilled.
	 */
	public void DOES (  )
	{
		super.DOES();
		generatedbyassl.as.autonomicnetwork.actions.CONFIGURATION.getInstance().perform(  );
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Triggers events in case the action is successfully performed.
	 */
	public void TRIGGERS (  )
	{
		generatedbyassl.as.autonomicnetwork.events.CONFIGURATIONDONE.getInstance().triggerEvent();
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Triggers events in case the action is not successfully performed.
	 */
	public void ONERR_TRIGGERS (  )
	{
		generatedbyassl.as.autonomicnetwork.events.CONFIGURATIONDENIED.getInstance().triggerEvent();
	}

}