package generatedbyassl.as.aes.controller.actions;

import java.io.Serializable;
import generatedbyassl.as.ASSLACTION;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'InspectTrafficType' (specified as ACTION ASSL tier).
 */
public class INSPECTTRAFFICTYPE
	extends ASSLACTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'INSPECTTRAFFICTYPE' class.
	 */
	static private INSPECTTRAFFICTYPE oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Action parameter.
	 */
	protected String TRAFFICTYPE = null;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  INSPECTTRAFFICTYPE (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'INSPECTTRAFFICTYPE' class.
	 */
	static public INSPECTTRAFFICTYPE getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new INSPECTTRAFFICTYPE();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Embeds statements to be performed by the action if the GURADS conditions are fulfilled.
	 */
	public void DOES (  )
	{
		super.DOES();
		if (  generatedbyassl.as.aes.controller.actions.INSPECTTRAFFICTYPE.getInstance().TRAFFICTYPE  ==  "ingress"  ) 
		{
			generatedbyassl.as.aes.controller.aeip.managed_elements.MONITORINGTOOL.getInstance().INGRESSTRAFFICCHECKER(  );
		}
		else if (  generatedbyassl.as.aes.controller.actions.INSPECTTRAFFICTYPE.getInstance().TRAFFICTYPE  ==  "egress"  ) 
		{
			generatedbyassl.as.aes.controller.aeip.managed_elements.MONITORINGTOOL.getInstance().EGRESSTRAFFICCHECKER(  );
		}
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Triggers events in case the action is successfully performed.
	 */
	public void TRIGGERS (  )
	{
		generatedbyassl.as.aes.controller.events.MONITORINGDONE.getInstance().triggerEvent();
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Performs the action (performs with default arguments).
	 */
	public synchronized void perform (  )
	{
		//**** Calls perform() with arguments by default.
		//**** If needed, change the arguments by default with appropriate ones.
		//****************************************************
		perform("");
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Performs the action.
	 */
	public synchronized void perform ( String TRAFFICTYPE )
	{
		this.TRAFFICTYPE = TRAFFICTYPE;
		super.perform();
	}

}