package generatedbyassl.as.aes;

import java.io.Serializable;
import generatedbyassl.as.ASSLAE;
import generatedbyassl.as.aes.controller.controlloop.*;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'Controller' (specified as AE ASSL tier).
 */
public class CONTROLLER
	extends ASSLAE
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'CONTROLLER' class.
	 */
	static private CONTROLLER oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the AE control loop's monitor.
	 */
	private CONTROLLER_ASSLMONITOR oMonitor = new CONTROLLER_ASSLMONITOR();
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the AE control loop's analyzer.
	 */
	private CONTROLLER_ASSLANALYZER oAnalyzer = new CONTROLLER_ASSLANALYZER();
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the AE control loop's simulator.
	 */
	private CONTROLLER_ASSLSIMULATOR oSimulator = new CONTROLLER_ASSLSIMULATOR();
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the AE control loop's executor.
	 */
	private CONTROLLER_ASSLEXECUTOR oExecutor = new CONTROLLER_ASSLEXECUTOR();
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the AEIP class.
	 */
	public generatedbyassl.as.aes.controller.AEIP AEIP = generatedbyassl.as.aes.controller.AEIP.getInstance();

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  CONTROLLER (  )
	{
		vPolicies.put( "SELF_CONFIGURING", generatedbyassl.as.aes.controller.aeself_management.SELF_CONFIGURING.getInstance() );
		ACTIONS.put( "STARTMONITORINGTOOL", generatedbyassl.as.aes.controller.actions.STARTMONITORINGTOOL.getInstance() );
		ACTIONS.put( "SELECTDATASOURCE", generatedbyassl.as.aes.controller.actions.SELECTDATASOURCE.getInstance() );
		ACTIONS.put( "INSPECTTRAFFIC", generatedbyassl.as.aes.controller.actions.INSPECTTRAFFIC.getInstance() );
		ACTIONS.put( "INSPECTTRAFFICTYPE", generatedbyassl.as.aes.controller.actions.INSPECTTRAFFICTYPE.getInstance() );
		EVENTS.put( "TIMETORUNMONITORINGTOOL", generatedbyassl.as.aes.controller.events.TIMETORUNMONITORINGTOOL.getInstance() );
		EVENTS.put( "MONITORINGTOOLSTARTED", generatedbyassl.as.aes.controller.events.MONITORINGTOOLSTARTED.getInstance() );
		EVENTS.put( "TIMETORUNSELECTDATASOURCE", generatedbyassl.as.aes.controller.events.TIMETORUNSELECTDATASOURCE.getInstance() );
		EVENTS.put( "DATASOURCESELECTED", generatedbyassl.as.aes.controller.events.DATASOURCESELECTED.getInstance() );
		EVENTS.put( "TIMETOINSPECTTRAFFIC", generatedbyassl.as.aes.controller.events.TIMETOINSPECTTRAFFIC.getInstance() );
		EVENTS.put( "TRAFFICINSPECTED", generatedbyassl.as.aes.controller.events.TRAFFICINSPECTED.getInstance() );
		EVENTS.put( "MONITORINGDONE", generatedbyassl.as.aes.controller.events.MONITORINGDONE.getInstance() );
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'CONTROLLER' class.
	 */
	static public CONTROLLER getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new CONTROLLER();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Sets the control loop components.
	 */
	protected void setControlLoop (  )
	{
		//**** This method overrides the super class's method.
		//****************************************************
		oMonitor.setMonitoredSLO(AESLO);
		oMonitor.setMonitoredMetrics(METRICS);
		oMonitor.setAnalyzer(oAnalyzer);
		oAnalyzer.setSimulator(oSimulator);
		oAnalyzer.setExecutor(oExecutor);
		oSimulator.setExecutor(oExecutor);
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Performs the AE control loop.
	 */
	protected void controlLoop (  )
	{
		//**** This method overrides the super class's method.
		//****************************************************
		try
		{
			//**** control loops should not be very resource-consuming, thus it releases CPU for a while
			Thread.sleep(1000);
		}
		catch ( InterruptedException ex ) 
		{
			System.err.println( ex.getMessage() );
		}
		//**** performs AE control loop monitor-analyzer-simulator-executor
		oMonitor.perform();
		oAnalyzer.perform();
		oSimulator.perform();
		oExecutor.perform();
		//**** applies all the "switched-on" self-management policies for the AS
		applayPolicies();
	}

}