package generatedbyassl.as.aes.controller.aeself_management.self_configuring;

import java.io.Serializable;
import generatedbyassl.as.*;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'inDataSourceSelection' (specified as FLUENT ASSL tier).
 */
public class INDATASOURCESELECTION
	extends ASSLFLUENT
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'INDATASOURCESELECTION' class.
	 */
	static private INDATASOURCESELECTION oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  INDATASOURCESELECTION (  )
	{
		vInitiatedByEvents.add( generatedbyassl.as.aes.controller.events.TIMETORUNSELECTDATASOURCE.getInstance() );
		generatedbyassl.as.aes.controller.events.TIMETORUNSELECTDATASOURCE.getInstance().addEventCatcher(this); //**** fluent registers for that event
		vTerminatedByEvents.add( generatedbyassl.as.aes.controller.events.DATASOURCESELECTED.getInstance() );
		generatedbyassl.as.aes.controller.events.DATASOURCESELECTED.getInstance().addEventCatcher(this); //**** fluent registers for that event
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'INDATASOURCESELECTION' class.
	 */
	static public INDATASOURCESELECTION getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new INDATASOURCESELECTION();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method calls all the fluent-mapped actions in sequence.
	 */
	protected synchronized void callFluentActions (  )
	{
	}

}