package generatedbyassl.as.aes.controller.aeself_management.self_configuring;

import java.io.Serializable;
import generatedbyassl.as.*;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'inStartMonitoringTool' (specified as FLUENT ASSL tier).
 */
public class INSTARTMONITORINGTOOL
	extends ASSLFLUENT
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'INSTARTMONITORINGTOOL' class.
	 */
	static private INSTARTMONITORINGTOOL oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  INSTARTMONITORINGTOOL (  )
	{
		vInitiatedByEvents.add( generatedbyassl.as.aes.controller.events.TIMETORUNMONITORINGTOOL.getInstance() );
		generatedbyassl.as.aes.controller.events.TIMETORUNMONITORINGTOOL.getInstance().addEventCatcher(this); //**** fluent registers for that event
		vTerminatedByEvents.add( generatedbyassl.as.aes.controller.events.MONITORINGTOOLSTARTED.getInstance() );
		generatedbyassl.as.aes.controller.events.MONITORINGTOOLSTARTED.getInstance().addEventCatcher(this); //**** fluent registers for that event
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'INSTARTMONITORINGTOOL' class.
	 */
	static public INSTARTMONITORINGTOOL getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new INSTARTMONITORINGTOOL();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method calls all the fluent-mapped actions in sequence.
	 */
	protected synchronized void callFluentActions (  )
	{
	}

}